name: New Bed Support Request
description: Request support for a new adjustable bed brand or model
title: "[New Bed] "
labels: ["new-bed", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request support for a new bed! The information you provide helps us implement the protocol correctly.

        **Before submitting:**
        - Check the [Supported Actuators guide](https://github.com/kristofferR/ha-adjustable-bed/blob/master/docs/SUPPORTED_ACTUATORS.md) to see if your bed might already be supported under a different actuator brand name
        - See the [Getting Help Guide](https://github.com/kristofferR/ha-adjustable-bed/blob/master/docs/GETTING_HELP.md#requesting-support-for-a-new-bed) for more details

  - type: input
    id: manufacturer
    attributes:
      label: Bed Manufacturer/Brand
      description: The brand name of your bed
      placeholder: "e.g., Tempur-Pedic, Sleep Number, Nectar"
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Bed Model
      description: The specific model name or number
      placeholder: "e.g., Ergo Extend"
    validations:
      required: true

  - type: input
    id: mobile_app
    attributes:
      label: Official Mobile App
      description: The name of the app you use to control your bed (check your app store)
      placeholder: "e.g., Tempur Ergo, Sleeptracker, Sven & Son, Reverie"
    validations:
      required: false

  - type: input
    id: remote_model
    attributes:
      label: Remote Control Model Number
      description: Check the back of your remote for a model number (optional but helpful)
      placeholder: "e.g., RF TOPLINE 82417"
    validations:
      required: false

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostic Report
      description: |
        **To generate a diagnostic report:**
        1. Add your bed to Home Assistant using "Diagnostic/Unknown" as the bed type
        2. Go to Developer Tools → Services
        3. Call `adjustable_bed.generate_support_report` for your bed
        4. Attach the generated JSON file here

        This report contains all the BLE information we need (service UUIDs, device name, etc.) and is the easiest way to provide technical details.
      placeholder: "Drag and drop the support report JSON file here"
    validations:
      required: true

  - type: textarea
    id: photos
    attributes:
      label: Photos
      description: |
        Please attach photos of:
        - Remote control (front and back)
        - Controller box under the bed (if accessible)
        - Any labels showing model numbers

        Drag and drop images here or paste from clipboard.
      placeholder: "Drag and drop images here"
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: |
        Any other helpful details:
        - Does the app require cloud login or work locally via Bluetooth?
        - Any special pairing requirements?
        - Does the bed work with voice assistants (Alexa, Google)?
      placeholder: "e.g., App works via Bluetooth only, no cloud required"
    validations:
      required: false

  - type: checkboxes
    id: testing
    attributes:
      label: Testing Availability
      description: Let us know if you can help test an implementation
      options:
        - label: I can test beta implementations on my bed
        - label: I have access to BLE debugging tools (nRF Connect, Wireshark, etc.)
